# frozen_string_literal: true

module Uniword
  module Cli
    # Builds shell completion scripts from live CLI metadata so new
    # commands appear in completions without editing the scripts.
    module Completions
      BUILTINS = %w[help completions].freeze

      module_function

      # @param shell [String] "bash", "zsh", or "fish"
      # @param root [Class] the root Thor class (Uniword::CLI)
      # @return [String] completion script
      def script(shell, root:)
        commands = root.all_commands.keys - BUILTINS
        subcommands = subcommand_map(root)

        case shell
        when "bash" then bash(commands, subcommands)
        when "zsh"  then zsh(commands, subcommands)
        when "fish" then fish(commands, subcommands)
        else
          raise ArgumentError,
                "unsupported shell: #{shell.inspect} (bash|zsh|fish)"
        end
      end

      # Map command name → registered subcommand Thor class, derived
      # from class names (ThemeCLI → "theme"), so `subcommand` call
      # sites stay the single source of truth.
      # Space-separated subcommand word list for one class.
      def words_for(klass)
        klass.all_commands.keys.reject { |c| c == "help" }.join(" ")
      end

      def subcommand_map(root)
        root.subcommand_classes.filter_map do |name, klass|
          [name, klass]
        end.to_h
      end

      def bash(commands, subcommands)
        cmds = commands.join(" ")
        script = <<~BASH
          # uniword bash completion — generated by `uniword completions bash`
          _uniword() {
            local cur="${COMP_WORDS[COMP_CWORD]}"
            local prev="${COMP_WORDS[COMP_CWORD-1]}"
            local cmds="#{cmds}"
        BASH
        subcommands.each do |name, klass|
          words = words_for(klass)
          script << "  if [ \"$prev\" = \"#{name}\" ]; then\n    " \
                    "COMPREPLY=( $(compgen -W \"#{words}\" " \
                    "-- \"$cur\") )\n    return\n  fi\n"
        end
        script << "  COMPREPLY=( $(compgen -W \"$cmds\" -- \"$cur\") )\n" \
                  "}\n" \
                  "complete -F _uniword uniword\n"
        script
      end

      def zsh(commands, subcommands)
        script = <<~ZSH
          #compdef uniword
          # uniword zsh completion — generated by `uniword completions zsh`
          _uniword() {
            local -a cmds
            cmds=(#{commands.map { |c| "'#{c}'" }.join(' ')})
            _describe 'command' cmds
        ZSH
        subcommands.each do |name, klass|
          words = words_for(klass).split.map { |c| "'#{c}'" }.join(" ")
          script << "  if (( CURRENT == 2 )) && [[ #{name} == * ]]; " \
                    "then\n    local -a sub\n    sub=(#{words})\n    " \
                    "_describe '#{name} command' sub\n  fi\n"
        end
        script << "}\n"
        script
      end

      def fish(commands, subcommands)
        script = +<<~FISH
          # uniword fish completion — generated by `uniword completions fish`
        FISH
        commands.each do |c|
          script << "complete -c uniword -n '__fish_use_subcommand' -a '#{c}'\n"
        end
        subcommands.each do |name, klass|
          words = words_for(klass)
          script << "complete -c uniword -n '__fish_seen_subcommand_from " \
                    "#{name}' -a '#{words}'\n"
        end
        script
      end
    end
  end
end
