#!/usr/bin/env ruby
# frozen_string_literal: true

# Advanced example for Uniword
# Demonstrates complex document creation with mixed content

require 'bundler/setup'
require 'uniword'

puts 'Creating an advanced document with mixed content...'

# Create document using Builder
doc = Uniword::Builder.new
                      .add_heading('Advanced Document Example', level: 1)
                      .add_paragraph('Created with Uniword - A unified Word document library', italic: true)
                      .add_blank_line
                      .build

# Executive Summary section
doc.add_element(
  Uniword::Paragraph.new
    .add_text('Executive Summary', bold: true, size: 32)
    .set_style('Heading2')
)

summary_text = 'This document demonstrates advanced features of Uniword including ' \
               'tables, formatted text, and complex document structures. ' \
               'It showcases the library\'s capability to handle real-world document creation scenarios.'

doc.add_element(
  Uniword::Paragraph.new
    .add_text(summary_text)
    .align('justify')
)

doc.add_element(Uniword::Paragraph.new.add_text(''))

# Features section
doc.add_element(
  Uniword::Paragraph.new
    .add_text('Key Features', bold: true, size: 32)
    .set_style('Heading2')
)

features = [
  'Fluent API for easy document construction',
  'Support for multiple formats (DOCX, MHTML)',
  'Rich text formatting capabilities',
  'Table creation and manipulation',
  'Style management'
]

features.each_with_index do |feature, i|
  para = Uniword::Paragraph.new
  para.add_text("#{i + 1}. ", bold: true)
  para.add_text(feature)
  doc.add_element(para)
end

doc.add_element(Uniword::Paragraph.new.add_text(''))

# Data table section
doc.add_element(
  Uniword::Paragraph.new
    .add_text('Performance Metrics', bold: true, size: 32)
    .set_style('Heading2')
)

# Create a detailed table
table = Uniword::Table.new

# Header row
header_row = Uniword::TableRow.new(header: true)
%w[Metric Q1 Q2 Q3 Q4].each do |header|
  cell = Uniword::TableCell.new
  para = Uniword::Paragraph.new
  para.add_text(header, bold: true).align('center')
  cell.add_paragraph(para)
  header_row.add_cell(cell)
end
table.add_row(header_row)

# Data rows
metrics = [
  ['Revenue ($M)', '125', '142', '158', '180'],
  ['Users (K)', '450', '520', '595', '680'],
  ['Growth (%)', '12', '14', '15', '14']
]

metrics.each do |row_data|
  row = Uniword::TableRow.new
  row_data.each_with_index do |value, i|
    cell = Uniword::TableCell.new
    para = Uniword::Paragraph.new
    if i.zero?
      para.add_text(value, bold: true)
    else
      para.add_text(value).align('right')
    end
    cell.add_paragraph(para)
    row.add_cell(cell)
  end
  table.add_row(row)
end

doc.add_element(table)
doc.add_element(Uniword::Paragraph.new.add_text(''))

# Conclusion section
doc.add_element(
  Uniword::Paragraph.new
    .add_text('Conclusion', bold: true, size: 32)
    .set_style('Heading2')
)

conclusion_parts = [
  ['Uniword provides a ', false],
  ['powerful', true],
  [' and ', false],
  ['flexible', true],
  [' solution for document generation in Ruby. ', false],
  [
    'Its object-oriented architecture makes it easy to create, modify, and convert documents programmatically.', false
  ]
]

conclusion_para = Uniword::Paragraph.new
conclusion_parts.each do |text, bold|
  conclusion_para.add_text(text, bold: bold)
end
conclusion_para.align('justify')
doc.add_element(conclusion_para)

doc.add_element(Uniword::Paragraph.new.add_text(''))

# Footer information
footer_para = Uniword::Paragraph.new
footer_para.add_text('Generated by Uniword v', italic: true, size: 18, color: '666666')
footer_para.add_text(Uniword::VERSION.to_s, italic: true, size: 18, color: '666666')
footer_para.align('center')
doc.add_element(footer_para)

# Save the document
output_dir = File.join(__dir__, 'output')
FileUtils.mkdir_p(output_dir)

output_path = File.join(output_dir, 'advanced_example.docx')
doc.save(output_path)

puts "✓ Created #{output_path}"
puts "  Paragraphs: #{doc.paragraphs.count}"
puts "  Tables: #{doc.tables.count}"
puts "  Total text length: #{doc.text.length} characters"
puts "\nAdvanced example complete!"
