# frozen_string_literal: true

# Chart Namespace Autoload Index
# Generated for Uniword v2.0 - Session 10
# Namespace: http://schemas.openxmlformats.org/drawingml/2006/chart
# Prefix: c
# Elements: 70

module Uniword
  module Chart
    # Chart Container (5 elements)
    autoload :ChartSpace, File.expand_path('chart/chart_space', __dir__)
    autoload :Chart, File.expand_path('chart/chart', __dir__)
    autoload :Title, File.expand_path('chart/title', __dir__)
    autoload :AutoTitleDeleted, File.expand_path('chart/auto_title_deleted', __dir__)
    autoload :PlotArea, File.expand_path('chart/plot_area', __dir__)
      
    # Chart Types (15 elements)
    autoload :BarChart, File.expand_path('chart/bar_chart', __dir__)
    autoload :Bar3DChart, File.expand_path('chart/bar3_d_chart', __dir__)
    autoload :LineChart, File.expand_path('chart/line_chart', __dir__)
    autoload :Line3DChart, File.expand_path('chart/line3_d_chart', __dir__)
    autoload :PieChart, File.expand_path('chart/pie_chart', __dir__)
    autoload :Pie3DChart, File.expand_path('chart/pie3_d_chart', __dir__)
    autoload :AreaChart, File.expand_path('chart/area_chart', __dir__)
    autoload :Area3DChart, File.expand_path('chart/area3_d_chart', __dir__)
    autoload :ScatterChart, File.expand_path('chart/scatter_chart', __dir__)
    autoload :RadarChart, File.expand_path('chart/radar_chart', __dir__)
    autoload :SurfaceChart, File.expand_path('chart/surface_chart', __dir__)
    autoload :Surface3DChart, File.expand_path('chart/surface3_d_chart', __dir__)
    autoload :DoughnutChart, File.expand_path('chart/doughnut_chart', __dir__)
    autoload :BubbleChart, File.expand_path('chart/bubble_chart', __dir__)
    autoload :StockChart, File.expand_path('chart/stock_chart', __dir__)
      
    # Series & Data (10 elements)
    autoload :Series, File.expand_path('chart/series', __dir__)
    autoload :Index, File.expand_path('chart/index', __dir__)
    autoload :Order, File.expand_path('chart/order', __dir__)
    autoload :SeriesText, File.expand_path('chart/series_text', __dir__)
    autoload :CategoryAxisData, File.expand_path('chart/category_axis_data', __dir__)
    autoload :Values, File.expand_path('chart/values', __dir__)
    autoload :XValues, File.expand_path('chart/x_values', __dir__)
    autoload :YValues, File.expand_path('chart/y_values', __dir__)
    autoload :BubbleSize, File.expand_path('chart/bubble_size', __dir__)
    autoload :NumberReference, File.expand_path('chart/number_reference', __dir__)
      
    # Axes (12 elements)
    autoload :CatAx, File.expand_path('chart/cat_ax', __dir__)
    autoload :ValAx, File.expand_path('chart/val_ax', __dir__)
    autoload :DateAx, File.expand_path('chart/date_ax', __dir__)
    autoload :SerAx, File.expand_path('chart/ser_ax', __dir__)
    autoload :AxisId, File.expand_path('chart/axis_id', __dir__)
    autoload :Scaling, File.expand_path('chart/scaling', __dir__)
    autoload :Orientation, File.expand_path('chart/orientation', __dir__)
    autoload :AxisPosition, File.expand_path('chart/axis_position', __dir__)
    autoload :MajorGridlines, File.expand_path('chart/major_gridlines', __dir__)
    autoload :MinorGridlines, File.expand_path('chart/minor_gridlines', __dir__)
    autoload :NumberingFormat, File.expand_path('chart/numbering_format', __dir__)
    autoload :TickLabelPosition, File.expand_path('chart/tick_label_position', __dir__)
      
    # Legend & Labels (8 elements)
    autoload :Legend, File.expand_path('chart/legend', __dir__)
    autoload :LegendPosition, File.expand_path('chart/legend_position', __dir__)
    autoload :LegendEntry, File.expand_path('chart/legend_entry', __dir__)
    autoload :DataLabels, File.expand_path('chart/data_labels', __dir__)
    autoload :DataLabel, File.expand_path('chart/data_label', __dir__)
    autoload :ShowLegendKey, File.expand_path('chart/show_legend_key', __dir__)
    autoload :ShowValue, File.expand_path('chart/show_value', __dir__)
    autoload :ShowCategoryName, File.expand_path('chart/show_category_name', __dir__)
      
    # Styling & Formatting (10 elements)
    autoload :ShapeProperties, File.expand_path('chart/shape_properties', __dir__)
    autoload :TextProperties, File.expand_path('chart/text_properties', __dir__)
    autoload :Style, File.expand_path('chart/style', __dir__)
    autoload :ColorMapOverride, File.expand_path('chart/color_map_override', __dir__)
    autoload :Marker, File.expand_path('chart/marker', __dir__)
    autoload :MarkerStyle, File.expand_path('chart/marker_style', __dir__)
    autoload :MarkerSize, File.expand_path('chart/marker_size', __dir__)
    autoload :Smooth, File.expand_path('chart/smooth', __dir__)
    autoload :Explosion, File.expand_path('chart/explosion', __dir__)
    autoload :GapWidth, File.expand_path('chart/gap_width', __dir__)
      
    # Advanced Features (10 elements)
    autoload :Trendline, File.expand_path('chart/trendline', __dir__)
    autoload :TrendlineType, File.expand_path('chart/trendline_type', __dir__)
    autoload :ErrorBars, File.expand_path('chart/error_bars', __dir__)
    autoload :ErrorDirection, File.expand_path('chart/error_direction', __dir__)
    autoload :ErrorBarType, File.expand_path('chart/error_bar_type', __dir__)
    autoload :UpDownBars, File.expand_path('chart/up_down_bars', __dir__)
    autoload :HiLowLines, File.expand_path('chart/hi_low_lines', __dir__)
    autoload :DropLines, File.expand_path('chart/drop_lines', __dir__)
    autoload :Layout, File.expand_path('chart/layout', __dir__)
    autoload :PlotVisOnly, File.expand_path('chart/plot_vis_only', __dir__)
  end
end
