# frozen_string_literal: true

# DrawingML Namespace Autoload Index
# Generated from: config/ooxml/schemas/drawingml.yml
# Namespace: http://schemas.openxmlformats.org/drawingml/2006/main
# Prefix: a
# Total classes: 92

module Uniword
  module Drawingml
    # Graphics primitives (6)
    autoload :Graphic, File.expand_path('drawingml/graphic', __dir__)
    autoload :GraphicData, File.expand_path('drawingml/graphic_data', __dir__)
    autoload :Blip, File.expand_path('drawingml/blip', __dir__)
    autoload :BlipFill, File.expand_path('drawingml/blip_fill', __dir__)
    autoload :Stretch, File.expand_path('drawingml/stretch', __dir__)
    autoload :SourceRect, File.expand_path('drawingml/source_rect', __dir__)
      
    # Shapes (4)
    autoload :Shape, File.expand_path('drawingml/shape', __dir__)
    autoload :NonVisualShapeProperties, File.expand_path('drawingml/non_visual_shape_properties', __dir__)
    autoload :NonVisualDrawingProperties, File.expand_path('drawingml/non_visual_drawing_properties', __dir__)
    autoload :ShapeProperties, File.expand_path('drawingml/shape_properties', __dir__)
      
    # Transforms (3)
    autoload :Transform2D, File.expand_path('drawingml/transform2_d', __dir__)
    autoload :Offset, File.expand_path('drawingml/offset', __dir__)
    autoload :Extents, File.expand_path('drawingml/extents', __dir__)
      
    # Lines (1)
    autoload :LineProperties, File.expand_path('drawingml/line_properties', __dir__)
      
    # Text (4)
    autoload :TextBody, File.expand_path('drawingml/text_body', __dir__)
    autoload :BodyProperties, File.expand_path('drawingml/body_properties', __dir__)
    autoload :TextParagraph, File.expand_path('drawingml/text_paragraph', __dir__)
    autoload :TextRun, File.expand_path('drawingml/text_run', __dir__)
      
    # Fills (2)
    autoload :SolidFill, File.expand_path('drawingml/solid_fill', __dir__)
    autoload :NoFill, File.expand_path('drawingml/no_fill', __dir__)
      
    # Colors (2)
    autoload :SrgbColor, File.expand_path('drawingml/srgb_color', __dir__)
    autoload :SchemeColor, File.expand_path('drawingml/scheme_color', __dir__)
      
    # Gradient fills (10)
    autoload :GradientStopList, File.expand_path('drawingml/gradient_stop_list', __dir__)
    autoload :GradientStop, File.expand_path('drawingml/gradient_stop', __dir__)
    autoload :LinearGradient, File.expand_path('drawingml/linear_gradient', __dir__)
    autoload :PathGradient, File.expand_path('drawingml/path_gradient', __dir__)
    autoload :FillToRect, File.expand_path('drawingml/fill_to_rect', __dir__)
    autoload :TileRect, File.expand_path('drawingml/tile_rect', __dir__)
    autoload :GradientFill, File.expand_path('drawingml/gradient_fill', __dir__)
    autoload :PatternFill, File.expand_path('drawingml/pattern_fill', __dir__)
    autoload :ForegroundColor, File.expand_path('drawingml/foreground_color', __dir__)
    autoload :BackgroundColor, File.expand_path('drawingml/background_color', __dir__)
      
    # Effects (15)
    autoload :EffectList, File.expand_path('drawingml/effect_list', __dir__)
    autoload :EffectContainer, File.expand_path('drawingml/effect_container', __dir__)
    autoload :Glow, File.expand_path('drawingml/glow', __dir__)
    autoload :InnerShadow, File.expand_path('drawingml/inner_shadow', __dir__)
    autoload :OuterShadow, File.expand_path('drawingml/outer_shadow', __dir__)
    autoload :PresetShadow, File.expand_path('drawingml/preset_shadow', __dir__)
    autoload :Reflection, File.expand_path('drawingml/reflection', __dir__)
    autoload :SoftEdge, File.expand_path('drawingml/soft_edge', __dir__)
    autoload :Blur, File.expand_path('drawingml/blur', __dir__)
    autoload :FillOverlay, File.expand_path('drawingml/fill_overlay', __dir__)
    autoload :Duotone, File.expand_path('drawingml/duotone', __dir__)
    autoload :AlphaBiLevel, File.expand_path('drawingml/alpha_bi_level', __dir__)
    autoload :AlphaModulationFixed, File.expand_path('drawingml/alpha_modulation_fixed', __dir__)
    autoload :BiLevel, File.expand_path('drawingml/bi_level', __dir__)
    autoload :Grayscale, File.expand_path('drawingml/grayscale', __dir__)
      
    # Color transforms (21)
    autoload :Alpha, File.expand_path('drawingml/alpha', __dir__)
    autoload :AlphaOffset, File.expand_path('drawingml/alpha_offset', __dir__)
    autoload :AlphaModulation, File.expand_path('drawingml/alpha_modulation', __dir__)
    autoload :Hue, File.expand_path('drawingml/hue', __dir__)
    autoload :HueOffset, File.expand_path('drawingml/hue_offset', __dir__)
    autoload :HueModulation, File.expand_path('drawingml/hue_modulation', __dir__)
    autoload :Saturation, File.expand_path('drawingml/saturation', __dir__)
    autoload :SaturationOffset, File.expand_path('drawingml/saturation_offset', __dir__)
    autoload :SaturationModulation, File.expand_path('drawingml/saturation_modulation', __dir__)
    autoload :Luminance, File.expand_path('drawingml/luminance', __dir__)
    autoload :LuminanceOffset, File.expand_path('drawingml/luminance_offset', __dir__)
    autoload :LuminanceModulation, File.expand_path('drawingml/luminance_modulation', __dir__)
    autoload :Red, File.expand_path('drawingml/red', __dir__)
    autoload :RedOffset, File.expand_path('drawingml/red_offset', __dir__)
    autoload :RedModulation, File.expand_path('drawingml/red_modulation', __dir__)
    autoload :Green, File.expand_path('drawingml/green', __dir__)
    autoload :Blue, File.expand_path('drawingml/blue', __dir__)
    autoload :Gamma, File.expand_path('drawingml/gamma', __dir__)
    autoload :InverseGamma, File.expand_path('drawingml/inverse_gamma', __dir__)
    autoload :Tint, File.expand_path('drawingml/tint', __dir__)
    autoload :Shade, File.expand_path('drawingml/shade', __dir__)
      
    # Shapes & geometry (9)
    autoload :PresetGeometry, File.expand_path('drawingml/preset_geometry', __dir__)
    autoload :CustomGeometry, File.expand_path('drawingml/custom_geometry', __dir__)
    autoload :AdjustValueList, File.expand_path('drawingml/adjust_value_list', __dir__)
    autoload :GeometryGuide, File.expand_path('drawingml/geometry_guide', __dir__)
    autoload :PathList, File.expand_path('drawingml/path_list', __dir__)
    autoload :MoveTo, File.expand_path('drawingml/move_to', __dir__)
    autoload :LineTo, File.expand_path('drawingml/line_to', __dir__)
    autoload :ArcTo, File.expand_path('drawingml/arc_to', __dir__)
    autoload :ClosePath, File.expand_path('drawingml/close_path', __dir__)
      
    # Text properties (10)
    autoload :ListStyle, File.expand_path('drawingml/list_style', __dir__)
    autoload :DefaultParagraphProperties, File.expand_path('drawingml/default_paragraph_properties', __dir__)
    autoload :Level1ParagraphProperties, File.expand_path('drawingml/level1_paragraph_properties', __dir__)
    autoload :Level2ParagraphProperties, File.expand_path('drawingml/level2_paragraph_properties', __dir__)
    autoload :Level3ParagraphProperties, File.expand_path('drawingml/level3_paragraph_properties', __dir__)
    autoload :TextParagraphProperties, File.expand_path('drawingml/text_paragraph_properties', __dir__)
    autoload :TextCharacterProperties, File.expand_path('drawingml/text_character_properties', __dir__)
    autoload :TextFont, File.expand_path('drawingml/text_font', __dir__)
    autoload :EastAsianFont, File.expand_path('drawingml/east_asian_font', __dir__)
    autoload :ComplexScriptFont, File.expand_path('drawingml/complex_script_font', __dir__)
      
    # Line properties (5)
    autoload :PresetDash, File.expand_path('drawingml/preset_dash', __dir__)
    autoload :CustomDash, File.expand_path('drawingml/custom_dash', __dir__)
    autoload :DashStop, File.expand_path('drawingml/dash_stop', __dir__)
    autoload :LineJoinRound, File.expand_path('drawingml/line_join_round', __dir__)
    autoload :LineJoinMiter, File.expand_path('drawingml/line_join_miter', __dir__)
  end
end
