# frozen_string_literal: true

module Uniword
  # Model attribute access helpers for lutaml-model classes.
  #
  # Provides read_attribute/write_attribute methods that call the public
  # getters/setters generated by lutaml-model for declared attributes.
  #
  # Validates that the attribute name exists in the model's schema before
  # dispatching through the model's public method table — only attributes
  # that are part of the model's declared public API can be accessed.
  module ModelAttributeAccess
    # Read a declared attribute's value by name.
    # @param name [Symbol] Declared attribute name
    # @return [Object] The attribute value
    # @raise [ArgumentError] if the attribute is not declared on the model
    def read_attribute(name)
      validate_declared_attribute!(name)
      method(name).call
    end

    # Write a declared attribute's value by name.
    # @param name [Symbol] Declared attribute name
    # @param value [Object] The value to assign
    # @raise [ArgumentError] if the attribute is not declared on the model
    def write_attribute(name, value)
      validate_declared_attribute!(name)
      method(:"#{name}=").call(value)
    end

    private

    # Validate that the attribute is declared in the model's schema.
    # @param name [Symbol, String] Attribute name
    # @raise [ArgumentError] if the attribute is not declared
    def validate_declared_attribute!(name)
      return if self.class.attributes.key?(name.to_sym)

      raise ArgumentError,
            "undeclared attribute #{name.inspect} for #{self.class}"
    end
  end
end
