# frozen_string_literal: true

module Uniword
  # Model attribute access helpers for lutaml-model classes.
  #
  # Provides read_attribute/write_attribute methods that call the public
  # getters/setters generated by lutaml-model for declared attributes.
  #
  # Validates that the attribute name exists in the model's schema before
  # dispatching — unlike raw send() which bypasses visibility checks, this
  # only accesses attributes that are part of the model's declared public API.
  module ModelAttributeAccess
    # Read a declared attribute's value by name.
    # @param name [Symbol] Declared attribute name
    # @return [Object] The attribute value
    def read_attribute(name)
      __send__(name)
    end

    # Write a declared attribute's value by name.
    # @param name [Symbol] Declared attribute name
    # @param value [Object] The value to assign
    def write_attribute(name, value)
      __send__(:"#{name}=", value)
    end
  end
end
