# frozen_string_literal: true

# Spreadsheetml namespace module
# This file explicitly autoloads all Spreadsheetml classes
# Using explicit autoload instead of dynamic Dir[] for maintainability
#
# SpreadsheetML namespace - Excel support
# Namespace: http://schemas.openxmlformats.org/spreadsheetml/2006/main
# Prefix: (none - default namespace in Excel files)

require 'lutaml/model'

module Uniword
  module Spreadsheetml
    # Autoload all Spreadsheetml classes (86)
    autoload :Alignment, 'uniword/spreadsheetml/alignment'
    autoload :Authors, 'uniword/spreadsheetml/authors'
    autoload :AutoFilter, 'uniword/spreadsheetml/auto_filter'
    autoload :Bold, 'uniword/spreadsheetml/bold'
    autoload :BookViews, 'uniword/spreadsheetml/book_views'
    autoload :Border, 'uniword/spreadsheetml/border'
    autoload :Borders, 'uniword/spreadsheetml/borders'
    autoload :CalcProperties, 'uniword/spreadsheetml/calc_properties'
    autoload :Cell, 'uniword/spreadsheetml/cell'
    autoload :CellFormat, 'uniword/spreadsheetml/cell_format'
    autoload :CellFormats, 'uniword/spreadsheetml/cell_formats'
    autoload :CellFormula, 'uniword/spreadsheetml/cell_formula'
    autoload :CellValue, 'uniword/spreadsheetml/cell_value'
    autoload :Chartsheet, 'uniword/spreadsheetml/chartsheet'
    autoload :Col, 'uniword/spreadsheetml/col'
    autoload :ColBreaks, 'uniword/spreadsheetml/col_breaks'
    autoload :Color, 'uniword/spreadsheetml/color'
    autoload :Cols, 'uniword/spreadsheetml/cols'
    autoload :Comment, 'uniword/spreadsheetml/comment'
    autoload :CommentList, 'uniword/spreadsheetml/comment_list'
    autoload :Comments, 'uniword/spreadsheetml/comments'
    autoload :ConditionalFormatting, 'uniword/spreadsheetml/conditional_formatting'
    autoload :ConditionalFormattingRule, 'uniword/spreadsheetml/conditional_formatting_rule'
    autoload :CustomWorkbookViews, 'uniword/spreadsheetml/custom_workbook_views'
    autoload :DataValidation, 'uniword/spreadsheetml/data_validation'
    autoload :DataValidations, 'uniword/spreadsheetml/data_validations'
    autoload :DefinedName, 'uniword/spreadsheetml/defined_name'
    autoload :DefinedNames, 'uniword/spreadsheetml/defined_names'
    autoload :Dimension, 'uniword/spreadsheetml/dimension'
    autoload :Drawing, 'uniword/spreadsheetml/drawing'
    autoload :ExternalReferences, 'uniword/spreadsheetml/external_references'
    autoload :FileSharing, 'uniword/spreadsheetml/file_sharing'
    autoload :FileVersion, 'uniword/spreadsheetml/file_version'
    autoload :Fill, 'uniword/spreadsheetml/fill'
    autoload :Fills, 'uniword/spreadsheetml/fills'
    autoload :FilterColumn, 'uniword/spreadsheetml/filter_column'
    autoload :Font, 'uniword/spreadsheetml/font'
    autoload :FontName, 'uniword/spreadsheetml/font_name'
    autoload :FontSize, 'uniword/spreadsheetml/font_size'
    autoload :Fonts, 'uniword/spreadsheetml/fonts'
    autoload :Hyperlink, 'uniword/spreadsheetml/hyperlink'
    autoload :Hyperlinks, 'uniword/spreadsheetml/hyperlinks'
    autoload :Italic, 'uniword/spreadsheetml/italic'
    autoload :LegacyDrawing, 'uniword/spreadsheetml/legacy_drawing'
    autoload :MergeCell, 'uniword/spreadsheetml/merge_cell'
    autoload :MergeCells, 'uniword/spreadsheetml/merge_cells'
    autoload :NumberFormat, 'uniword/spreadsheetml/number_format'
    autoload :NumberFormats, 'uniword/spreadsheetml/number_formats'
    autoload :OleObject, 'uniword/spreadsheetml/ole_object'
    autoload :OleObjects, 'uniword/spreadsheetml/ole_objects'
    autoload :PatternFill, 'uniword/spreadsheetml/pattern_fill'
    autoload :PhoneticProperties, 'uniword/spreadsheetml/phonetic_properties'
    autoload :PivotCaches, 'uniword/spreadsheetml/pivot_caches'
    autoload :PivotTable, 'uniword/spreadsheetml/pivot_table'
    autoload :PivotTableDefinition, 'uniword/spreadsheetml/pivot_table_definition'
    autoload :ProtectedRanges, 'uniword/spreadsheetml/protected_ranges'
    autoload :QueryTable, 'uniword/spreadsheetml/query_table'
    autoload :RichTextRun, 'uniword/spreadsheetml/rich_text_run'
    autoload :Row, 'uniword/spreadsheetml/row'
    autoload :RowBreaks, 'uniword/spreadsheetml/row_breaks'
    autoload :RunProperties, 'uniword/spreadsheetml/run_properties'
    autoload :Scenarios, 'uniword/spreadsheetml/scenarios'
    autoload :SharedStringTable, 'uniword/spreadsheetml/shared_string_table'
    autoload :Sheet, 'uniword/spreadsheetml/sheet'
    autoload :SheetData, 'uniword/spreadsheetml/sheet_data'
    autoload :SheetProtection, 'uniword/spreadsheetml/sheet_protection'
    autoload :SheetView, 'uniword/spreadsheetml/sheet_view'
    autoload :SheetViews, 'uniword/spreadsheetml/sheet_views'
    autoload :Sheets, 'uniword/spreadsheetml/sheets'
    autoload :SortState, 'uniword/spreadsheetml/sort_state'
    autoload :SparklineGroup, 'uniword/spreadsheetml/sparkline_group'
    autoload :SparklineGroups, 'uniword/spreadsheetml/sparkline_groups'
    autoload :StringItem, 'uniword/spreadsheetml/string_item'
    autoload :Table, 'uniword/spreadsheetml/table'
    autoload :TableColumn, 'uniword/spreadsheetml/table_column'
    autoload :TableColumns, 'uniword/spreadsheetml/table_columns'
    autoload :TableStyleInfo, 'uniword/spreadsheetml/table_style_info'
    autoload :Text, 'uniword/spreadsheetml/text'
    autoload :Workbook, 'uniword/spreadsheetml/workbook'
    autoload :WorkbookProperties, 'uniword/spreadsheetml/workbook_properties'
    autoload :WorkbookProtection, 'uniword/spreadsheetml/workbook_protection'
    autoload :WorkbookView, 'uniword/spreadsheetml/workbook_view'
    autoload :Worksheet, 'uniword/spreadsheetml/worksheet'
  end
end
