# frozen_string_literal: true

# Ensure Ooxml module is loaded first (needed for typed attributes)
require_relative 'ooxml'

module Uniword
  module Wordprocessingml
    # Core document structure
    autoload :DocumentRoot, 'uniword/wordprocessingml/document_root'
    autoload :Body, 'uniword/wordprocessingml/body'
    autoload :Paragraph, 'uniword/wordprocessingml/paragraph'
    autoload :Run, 'uniword/wordprocessingml/run'
    autoload :Table, 'uniword/wordprocessingml/table'
    autoload :TableRow, 'uniword/wordprocessingml/table_row'
    autoload :TableCell, 'uniword/wordprocessingml/table_cell'
    autoload :TableGrid, 'uniword/wordprocessingml/table_grid'

    # Paragraph elements
    autoload :Hyperlink, 'uniword/wordprocessingml/hyperlink'
    autoload :BookmarkStart, 'uniword/wordprocessingml/bookmark_start'
    autoload :BookmarkEnd, 'uniword/wordprocessingml/bookmark_end'
    autoload :FieldChar, 'uniword/wordprocessingml/field_char'
    autoload :InstrText, 'uniword/wordprocessingml/instr_text'
    autoload :ProofErr, 'uniword/wordprocessingml/proof_err'
    autoload :CommentRangeStart, 'uniword/wordprocessingml/comment_range_start'
    autoload :CommentRangeEnd, 'uniword/wordprocessingml/comment_range_end'
    autoload :CommentReference, 'uniword/wordprocessingml/comment_reference'

    # Run elements
    autoload :Tab, 'uniword/wordprocessingml/tab'
    autoload :Break, 'uniword/wordprocessingml/break'
    autoload :Pict, 'uniword/wordprocessingml/pict'
    autoload :Symbol, 'uniword/wordprocessingml/symbol'
    autoload :TextBoxContent, 'uniword/wordprocessingml/text_box_content'
    autoload :Object, 'uniword/wordprocessingml/object'

    # Compatibility
    autoload :AlternateContent, 'uniword/wordprocessingml/alternate_content'
    autoload :Choice, 'uniword/wordprocessingml/choice'
    autoload :Fallback, 'uniword/wordprocessingml/fallback'
    autoload :McRequires, 'uniword/wordprocessingml/mc_requires'
    autoload :Compat, 'uniword/wordprocessingml/compat'
    autoload :CompatSetting, 'uniword/wordprocessingml/compat_setting'

    # Drawing and graphics
    autoload :Drawing, 'uniword/wordprocessingml/drawing'
    autoload :Anchor, 'uniword/wordprocessingml/anchor'
    autoload :Inline, 'uniword/wordprocessingml/inline'
    autoload :Extent, 'uniword/wordprocessingml/extent'
    autoload :DocPr, 'uniword/wordprocessingml/doc_pr'
    autoload :SimplePos, 'uniword/wordprocessingml/simple_pos'
    autoload :Graphic, 'uniword/wordprocessingml/graphic'
    autoload :GraphicData, 'uniword/wordprocessingml/graphic_data'
    autoload :Picture, 'uniword/wordprocessingml/picture'
    autoload :Shape, 'uniword/wordprocessingml/shape'

    # Structure and metadata
    autoload :Level, 'uniword/wordprocessingml/level'
    autoload :Style, 'uniword/wordprocessingml/style'
    autoload :StructuredDocumentTag, 'uniword/wordprocessingml/structured_document_tag'
    autoload :StructuredDocumentTagProperties, 'uniword/wordprocessingml/structured_document_tag_properties'
    autoload :SectionProperties, 'uniword/wordprocessingml/section_properties'
    autoload :PageSize, 'uniword/wordprocessingml/page_size'
    autoload :PageMargins, 'uniword/wordprocessingml/page_margins'
    autoload :PageNumbering, 'uniword/wordprocessingml/page_numbering'
    autoload :Columns, 'uniword/wordprocessingml/columns'
    autoload :HeaderReference, 'uniword/wordprocessingml/header_reference'
    autoload :FooterReference, 'uniword/wordprocessingml/footer_reference'
    autoload :Header, 'uniword/wordprocessingml/header'
    autoload :Footer, 'uniword/wordprocessingml/footer'

    # Document settings and defaults
    autoload :Settings, 'uniword/wordprocessingml/settings'
    autoload :ProofState, 'uniword/wordprocessingml/settings'
    autoload :StylePaneFormatFilter, 'uniword/wordprocessingml/settings'
    autoload :DefaultTabStop, 'uniword/wordprocessingml/settings'
    autoload :CharacterSpacingControl, 'uniword/wordprocessingml/settings'
    autoload :Rsids, 'uniword/wordprocessingml/settings'
    autoload :RsidRoot, 'uniword/wordprocessingml/settings'
    autoload :Rsid, 'uniword/wordprocessingml/settings'
    autoload :MathPr, 'uniword/wordprocessingml/settings'
    autoload :MathFont, 'uniword/wordprocessingml/settings'
    autoload :BrkBin, 'uniword/wordprocessingml/settings'
    autoload :BrkBinSub, 'uniword/wordprocessingml/settings'
    autoload :SmallFrac, 'uniword/wordprocessingml/settings'
    autoload :DispDef, 'uniword/wordprocessingml/settings'
    autoload :LMargin, 'uniword/wordprocessingml/settings'
    autoload :RMargin, 'uniword/wordprocessingml/settings'
    autoload :DefJc, 'uniword/wordprocessingml/settings'
    autoload :WrapIndent, 'uniword/wordprocessingml/settings'
    autoload :IntLim, 'uniword/wordprocessingml/settings'
    autoload :NaryLim, 'uniword/wordprocessingml/settings'
    autoload :ThemeFontLang, 'uniword/wordprocessingml/settings'
    autoload :ClrSchemeMapping, 'uniword/wordprocessingml/settings'
    autoload :ShapeDefaults, 'uniword/wordprocessingml/settings'
    autoload :DecimalSymbol, 'uniword/wordprocessingml/settings'
    autoload :ListSeparator, 'uniword/wordprocessingml/settings'
    autoload :W14DocId, 'uniword/wordprocessingml/settings'
    autoload :W15ChartTrackingRefBased, 'uniword/wordprocessingml/settings'
    autoload :W15DocId, 'uniword/wordprocessingml/settings'
    autoload :ProofState, 'uniword/wordprocessingml/settings'
    autoload :StylePaneFormatFilter, 'uniword/wordprocessingml/settings'
    autoload :DefaultTabStop, 'uniword/wordprocessingml/settings'
    autoload :CharacterSpacingControl, 'uniword/wordprocessingml/settings'
    autoload :Rsids, 'uniword/wordprocessingml/settings'
    autoload :RsidRoot, 'uniword/wordprocessingml/settings'
    autoload :Rsid, 'uniword/wordprocessingml/settings'
    autoload :MathPr, 'uniword/wordprocessingml/settings'
    autoload :MathFont, 'uniword/wordprocessingml/settings'
    autoload :BrkBin, 'uniword/wordprocessingml/settings'
    autoload :BrkBinSub, 'uniword/wordprocessingml/settings'
    autoload :SmallFrac, 'uniword/wordprocessingml/settings'
    autoload :DispDef, 'uniword/wordprocessingml/settings'
    autoload :LMargin, 'uniword/wordprocessingml/settings'
    autoload :RMargin, 'uniword/wordprocessingml/settings'
    autoload :DefJc, 'uniword/wordprocessingml/settings'
    autoload :WrapIndent, 'uniword/wordprocessingml/settings'
    autoload :IntLim, 'uniword/wordprocessingml/settings'
    autoload :NaryLim, 'uniword/wordprocessingml/settings'
    autoload :ThemeFontLang, 'uniword/wordprocessingml/settings'
    autoload :ClrSchemeMapping, 'uniword/wordprocessingml/settings'
    autoload :ShapeDefaults, 'uniword/wordprocessingml/settings'
    autoload :DecimalSymbol, 'uniword/wordprocessingml/settings'
    autoload :ListSeparator, 'uniword/wordprocessingml/settings'
    autoload :SemiHidden, 'uniword/wordprocessingml/semi_hidden'
    autoload :UnhideWhenUsed, 'uniword/wordprocessingml/semi_hidden'
    autoload :LatentStylesException, 'uniword/wordprocessingml/latent_styles'
    autoload :DocDefaults, 'uniword/wordprocessingml/doc_defaults'
    autoload :Zoom, 'uniword/wordprocessingml/zoom'

    # Fonts
    autoload :Font, 'uniword/wordprocessingml/font'
    autoload :Fonts, 'uniword/wordprocessingml/fonts'
    autoload :FontTable, 'uniword/wordprocessingml/font_table'
    autoload :WebSettings, 'uniword/wordprocessingml/web_settings'

    # Numbering
    autoload :AbstractNum, 'uniword/wordprocessingml/abstract_num'
    autoload :AbstractNumId, 'uniword/wordprocessingml/numbering_elements'
    autoload :Num, 'uniword/wordprocessingml/num'
    autoload :Numbering, 'uniword/wordprocessingml/numbering'
    autoload :MultiLevelType, 'uniword/wordprocessingml/multi_level_type'
    autoload :Nsid, 'uniword/wordprocessingml/numbering_elements'
    autoload :Tmpl, 'uniword/wordprocessingml/numbering_elements'
    autoload :Start, 'uniword/wordprocessingml/start'
    autoload :NumFmt, 'uniword/wordprocessingml/num_fmt'
    autoload :LvlText, 'uniword/wordprocessingml/lvl_text'
    autoload :LvlJc, 'uniword/wordprocessingml/lvl_jc'
    autoload :Ind, 'uniword/wordprocessingml/numbering_elements'
    autoload :RFonts, 'uniword/wordprocessingml/numbering_elements'
    autoload :Tabs, 'uniword/wordprocessingml/level'
    autoload :PStyle, 'uniword/wordprocessingml/level'
    autoload :NumberingConfiguration, 'uniword/wordprocessingml/numbering_configuration'
    autoload :NumberingDefinition, 'uniword/wordprocessingml/numbering_definition'
    autoload :NumberingInstance, 'uniword/wordprocessingml/numbering_instance'
    autoload :NumberingLevel, 'uniword/wordprocessingml/numbering_level'
    autoload :StylesConfiguration, 'uniword/wordprocessingml/styles_configuration'

    # Footnotes and endnotes
    autoload :Footnote, 'uniword/wordprocessingml/footnote'
    autoload :FootnoteReference, 'uniword/wordprocessingml/footnote_reference'
    autoload :Footnotes, 'uniword/wordprocessingml/footnotes'
    autoload :Endnote, 'uniword/wordprocessingml/endnote'
    autoload :EndnoteReference, 'uniword/wordprocessingml/endnote_reference'
    autoload :Endnotes, 'uniword/wordprocessingml/endnotes'

    # Style elements
    autoload :StyleName, 'uniword/wordprocessingml/style_name'
    autoload :BasedOn, 'uniword/wordprocessingml/based_on'
    autoload :Next, 'uniword/wordprocessingml/next'
    autoload :Link, 'uniword/wordprocessingml/link'
    autoload :UiPriority, 'uniword/wordprocessingml/ui_priority'
    autoload :LatentStyles, 'uniword/wordprocessingml/latent_styles'
    autoload :ParagraphStyle, 'uniword/wordprocessingml/paragraph_style'
    autoload :CharacterStyle, 'uniword/wordprocessingml/character_style'

    # Text effects
    autoload :Emboss, 'uniword/wordprocessingml/emboss'
    autoload :Imprint, 'uniword/wordprocessingml/imprint'
    autoload :Outline, 'uniword/wordprocessingml/outline'
    autoload :Shadow, 'uniword/wordprocessingml/shadow'

    # Properties
    autoload :TableCellProperties, 'uniword/wordprocessingml/table_cell_properties'
    autoload :TableRowProperties, 'uniword/wordprocessingml/table_row_properties'
    autoload :TableCellBorders, 'uniword/wordprocessingml/table_cell_borders'
    autoload :Border, 'uniword/wordprocessingml/border'
    autoload :ParagraphBorders, 'uniword/wordprocessingml/paragraph_borders'
    autoload :TableBorders, 'uniword/wordprocessingml/table_borders'
    autoload :RPrDefault, 'uniword/wordprocessingml/r_pr_default'
    autoload :PPrDefault, 'uniword/wordprocessingml/p_pr_default'
    autoload :Shading, 'uniword/wordprocessingml/shading'
    autoload :TabStop, 'uniword/wordprocessingml/tab_stop'

    # Properties classes (consolidated from Ooxml::WordProcessingML)
    autoload :ParagraphProperties, 'uniword/wordprocessingml/paragraph_properties'
    autoload :RunProperties, 'uniword/wordprocessingml/run_properties'
    autoload :TableProperties, 'uniword/wordprocessingml/table_properties'

    autoload :W14ParaId, 'uniword/wordprocessingml/w14_attributes'
    autoload :W14TextId, 'uniword/wordprocessingml/w14_attributes'
    autoload :W15RestartNumberingAfterBreak, 'uniword/wordprocessingml/w14_attributes'
    autoload :W16CidDurableId, 'uniword/wordprocessingml/w14_attributes'
    autoload :DocGrid, 'uniword/wordprocessingml/doc_grid'
    autoload :Text, 'uniword/wordprocessingml/text'

    # Grid
    autoload :GridCol, 'uniword/wordprocessingml/grid_col'
  end
end
