name: rake

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout private fixtures
        uses: actions/checkout@v4
        with:
          repository: metanorma/uniword-private
          token: ${{ secrets.GH_PAT }}
          path: main/spec/fixtures/uniword-private

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: main

      - name: Run tests
        run: bundle exec rake spec
        working-directory: main

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop